version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=final_model
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - API_URL=http://backend:8000/
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge