name: MIFI_Hackaton_Polyglot_News_Analyzer     # имя окружения
channels:
  - conda-forge
  - pytorch
  - defaults            # чтобы убрать предупреждение про «defaults»

dependencies:
  - python=3.10
  - pandas
  - openpyxl
  - scikit-learn
  - numpy=1.23          # фиксированная версия NumPy для совместимости

  # ─── PyTorch с поддержкой CUDA 11.8 ───────────────────
  - pytorch=2.2         # основной пакет PyTorch
  - cudatoolkit=11.8    # соответствующий CUDA Toolkit

  # ─── NLP / DL остальное ───────────────────────────────
  - transformers
  - datasets

  # ─── Jupyter & utilities ──────────────────────────────
  - ipykernel
  - jupyterlab
  - ipywidgets          # добавляем ipywidgets через conda

  # ─── Визуализация ─────────────────────────────────────
  - matplotlib          # добавляем matplotlib через conda

  # ─── Optuna для оптимизации гиперпараметров ───────────
  - optuna              # добавляем optuna через conda

  - pip
  - pip:
      - accelerate
      - scikit-multilearn  # добавляем skmultilearn через pip