name: MIFI_Hackaton_Polyglot_News_Analyzer     # имя окружения
channels:
  - conda-forge
  - pytorch
  - defaults            # чтобы убрать предупреждение про «defaults»

dependencies:
  - python=3.10
  - pandas
  - openpyxl
  - scikit-learn
  - numpy

  # ─── PyTorch с поддержкой CUDA 11.8 ───────────────────
  - pytorch=2.2         # основной пакет PyTorch
  - cudatoolkit=11.8    # соответствующий CUDA Toolkit

  # ─── NLP / DL остальное ───────────────────────────────
  - transformers
  - datasets

  # ─── Jupyter & utilities ──────────────────────────────
  - ipykernel
  - jupyterlab

  - pip
  - pip:
      - accelerate